project_id = "elewyvljdddyxretrwyw"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[functions.ai-research-assistant]
verify_jwt = false

[functions.import-publications]
verify_jwt = false
